config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :post_comments
  end
  
  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :team
  has_many :post_comments
end
  

app/models/post_comment.rb
class PostComment < ActiveRecord::Base
  validates_presence_of :comment
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  # For the dropdown menu in Blog Posts
  def set_team_options
     @mlb_teams =
      ["Yankees", "Yankees"],
      ["Orioles", "Orioles"],
      ["Red Sox", "Red Sox"],
      ["Blue Jays", "Blue Jays"],
      ["Rays", "Rays"],
      ["White Sox", "White Sox"],
      ["Indians", "Indians"],
      ["Tigers", "Tigers"],
      ["Royals", "Royals"],
      ["Twins", "Twins"],
      ["Astros", "Astros"],
      ["Angels", "Angels"],
      ["Atheltics", "Athletics"],
      ["Mariners", "Mariners"],
      ["Rangers", "Rangers"],
      ["Giants", "Giants"],
      ["Padres", "Padres"],
      ["Dodgers", "Dodgers"],
      ["Rockies", "Rockies"],
      ["Diamondbacks", "Diamondbacks"],
      ["Cardinals", "Cardinals"],
      ["Pirates", "Pirates"],
      ["Brewers", "Brewers"],
      ["Reds", "Reds"],
      ["Cubs", "Cubs"],
      ["Braves", "Braves"],
      ["Marlins", "Marlins"],
      ["Mets", "Mets"],
      ["Phillies", "Phillies"],
      ["Nationals", "Nationals"]
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  
  before_action :find_todo_list
  
  def index
    @post_comment = @post.post_comments.all
  end
  
  def show
    @post_comment = @post.post_comments.find(params[:id])
  end

  def new
    @post_comment = @post.post_comments.new
  end
  
  def edit
    @post_comment = @post.post_comments.find(params[:id])
  end
  
  def create
    @post_comment = @post.post_comments.new(post_comment_params)
    if 
      @post_comment.save
      redirect_to post_post_comments_path
      flash[:success] = "Comment added successfully!"
    else
      render 'new'
    end
  end

  def update
    @post_comment = @post.post_comments.find(params[:id])
    if
      @post_comment.update(post_comment_params)
      redirect_to post_post_comment_path
      flash[:success] = "Comment successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
    @post_comment = @post.post_comments.find(params[:id])
    @post_comment.destroy
    
    redirect_to post_post_comments_path
    flash[:success] = "The comment was successfully deleted"
  end
end

private

  def find_todo_list
    @post = Post.find(params[:post_id])
  end
 
  def post_comment_params
    params[:post_comment].permit(:comment)
  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_team_options
   
  def index
    @post = Post.all
  end
  
  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
      flash[:success] = "The post was successfully created!"
    else 
      render 'new'
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
      flash[:success] = "The post has been updated successfully!"
    else
      render 'edit'
    end
  end   
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    flash[:success] = "Post successfully deleted"
    redirect_to root_path
  end
end

  
private
def post_params
  params.require(:post).permit(:title, :description, :team)
end
  
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title id="baseball">Baseball Blog</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'normalize', media: 'all', 'data-tubolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header_wrapper">
  <nav class="nav_bar">
    <%= link_to "Home", posts_path %>
    <%= link_to "New Post", new_post_path %>
  </nav>
  </div>
  <% flash.each do |atr, msg| %>
  <div class="alert_<%=atr%>_message"><%=msg%></div>
  <% end %>
  
  <div class="container">
  <%= yield %>
  </div>
  
  <div class="footer_wrapper">
  <footer>
    <span>Copyright @adam graham 2016</span>
  </footer>
  </div>
  
</body>
</html>

app/views/post_comments/_form.html.erb
<%= form_for [@post, @post_comment] do |f| %>
<% if @post_comment.errors.any? %>
<div id ="error_explanation">
  <h2><%= pluralize(@post_comment.errors.count, "error")%> prohibited this article from being saved:</h2>
  
  <ul>
    <% @post_comment.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>
<br>
  <div>
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>

  <div>
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/post_comments/edit.html.erb
<h1>Update Comment for <%=@post.title%></h1>

<%= render 'form' %>

app/views/post_comments/index.html.erb
<h1>Comments for <%=@post.title%></h1>
<body>
<table>
  <tbody>
    <th>Comments</th>
    <% @post.post_comments.each do |comment| %>
    <tr id="<%=dom_id(comment)%>">
    <td><%=comment.comment%></td>
      <td><%= link_to "Edit", edit_post_post_comment_path(@post, comment)%></td>
      <td><%= link_to "Delete", post_post_comment_path(@post, comment), method: :delete, data: {confirm: 'Are you sure you want to delete this post?'}%></td>
      <br>
    </tr>
  </tbody>
</table>
</body>
<% end %>
<br>
<%=link_to "Add Comment", new_post_post_comment_path%>
<%=link_to "Back", root_path%>

app/views/post_comments/new.html.erb
<h1>New comment for <%=@post.title%></h1>

<%= render 'form' %>

app/views/post_comments/show.html.erb
<h1>Showing Comment</h1>
<p>Comment: <%= @post_comment.comment %></p>
<%= link_to "Back", post_post_comments_path %>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<% if @post.errors.any? %>
<div id ="error_explanation">
<h2><%= pluralize(@post.errors.count, "error")%> prohibited this article from being saved:</h2>

  <ul>
  <% @post.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>
<br>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div>
    <%= f.label "Team this post is about:" %>
    <%= f.select :team, options_for_select(@mlb_teams)%>
  </div>
  
  <div>
    <%= f.submit %>
  </div>
  
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%=link_to 'Back', root_path %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<body>
<table class="post_table">
  <tbody>
    <th>Title</th>
    <th>Description</th>
    <th>Team post is about</th>
    <% @post.each do |post| %>
    <tr id="<%=dom_id(post)%>">
      <td rowspan = "7"><%= post.title %></td>
      <td><%= post.description %></td>
      <td><%= post.team %></td>
      <td><%= link_to "Edit", edit_post_path(post)%></td>
      <td><%= link_to "Delete", post, method: :delete, data:{confirm: 'Are you sure you want to delete this post?'}%></td>
      <td><%= link_to "Show", post %></td>
      <td><%= link_to "Comments", post_post_comments_path(post)%></td>
      <br>
    </tr>
  </tbody>
</table>
</body>
<% end %>
<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%=link_to 'Back', root_path%>

app/views/posts/show.html.erb
<h1>Showing Post</h1>
<p>Title: <%= @post.title %></p>
<p>Description: <%= @post.description %></p>
<p>This post is about the <%= @post.team %></p>
<%= link_to "Back", root_path %>